- name: Install cargo-binstall
  uses: cargo-bins/cargo-binstall@main
- name: Install wasm-bindgen-cli
  shell: bash
  run: |
    VERSION=$(cargo metadata --format-version 1 | jq -r '.packages[] | select(.name == "wasm-bindgen") | .version' | head -1)
    echo "Installing wasm-bindgen-cli@$VERSION"
    cargo binstall "wasm-bindgen-cli@=$VERSION" -y --force
- name: Add wasm32 target
  run: rustup target add wasm32-unknown-unknown
- name: Build livereload-client WASM
  run: |
    cargo build -p livereload-client --target wasm32-unknown-unknown --release
    wasm-bindgen --target web --out-dir crates/livereload-client/pkg target/wasm32-unknown-unknown/release/livereload_client.wasm
